In [2]:
import torch
torch.__version__

'1.11.0'

In [2]:
x=torch.empty(5,3)
x

tensor([[9.2755e-39, 1.0561e-38, 4.7756e-39],
        [4.6837e-39, 4.4082e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])

In [9]:
x=torch.rand(5,3)
x

tensor([[0.0224, 0.4560, 0.7481],
        [0.9637, 0.9169, 0.1437],
        [0.1362, 0.3859, 0.7125],
        [0.8941, 0.6735, 0.7307],
        [0.8492, 0.9666, 0.2795]])

tensor是pytorch最底层的

初始化全零矩阵

In [10]:
x=torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [11]:
x.size()

torch.Size([5, 3])

基本计算方法，直接进行加减，索引同python

view操作可以改变矩阵维度，-1是自动计算

In [12]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


与Numpy的协同操作

In [14]:
a=torch.ones(5)
b=a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [15]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)